services:
  docusaurus:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./apps/website/blog:/app/website/blog
      - ./apps/website/docs:/app/website/docs
      - ./apps/website/src:/app/website/src
      - ./apps/website/static:/app/website/static
      - ./apps/website/sidebars.ts:/app/website/sidebars.ts
      - ./apps/website/docusaurus.config.ts:/app/website/docusaurus.config.ts
    working_dir: /app/website
