export const MAILER_OPTIONS = 'MAILER_OPTIONS';
export const MAILER_TRANSPORT_FACTORY = 'MAILER_TRANSPORT_FACTORY';
export const MAILER_TEMPLATE_RESOLVER = 'MAILER_TEMPLATE_RESOLVER';
export const MAILER_QUEUE_OPTIONS = 'MAILER_QUEUE_OPTIONS';
